import puppeteerCore from "puppeteer-core";
import puppeteer from "puppeteer"; // Import standard puppeteer for local use
import chromium from "@sparticuz/chromium";
import { getFullHtml } from "./pdfTemplate.js";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function getImageAsBase64(filePath) {
  try {
    const file = fs.readFileSync(filePath);
    return `data:image/png;base64,${Buffer.from(file).toString("base64")}`;
  } catch (error) {
    console.error("Could not read logo file for PDF header:", error);
    return "";
  }
}

export async function generateVisitReport(visit, patient) {
  let browser = null;
  try {
    const logoPath = path.join(__dirname, "../assets/clinic-logo.png");
    const logoBase64 = getImageAsBase64(logoPath);

    const clinicInfo = {
      name: "Candelaria Eye Care Clinic",
      address:
        "2nd, APC Building CKCI Dialysis Center, Maharlika Highway, Brgy. Masic Sur, 4323 Candelaria, Quezon",
      contact: "candelariaeyecare@gmail.com | 0917 123 4567",
    };

    // --- DETECT ENVIRONMENT ---
    // Render automatically sets 'RENDER' to true.
    // Usually NODE_ENV is set to 'production' in deployments.
    const isProduction =
      process.env.NODE_ENV === "production" || process.env.RENDER;

    if (isProduction) {
      // --- PRODUCTION (RENDER) SETTINGS ---
      browser = await puppeteerCore.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath(),
        headless: chromium.headless,
        ignoreHTTPSErrors: true,
      });
    } else {
      // --- LOCAL DEVELOPMENT SETTINGS ---
      browser = await puppeteer.launch({
        headless: "new",
        args: ["--no-sandbox", "--disable-setuid-sandbox"], // Standard args for stability
      });
    }

    const page = await browser.newPage();

    const htmlContent = getFullHtml(patient, visit, clinicInfo);

    await page.setContent(htmlContent, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "130px", bottom: "70px", left: "50px", right: "50px" },
      displayHeaderFooter: true,
      headerTemplate: `
          <div style="width: 100%; border-bottom: 1px solid #EAEAEA; padding: 0 50px; box-sizing: border-box; font-family: Helvetica, Arial, sans-serif;">
              <div style="display: flex; justify-content: space-between; align-items: flex-start; padding-top: 40px;">
                  <img src="${logoBase64}" style="width: 60px;"/>
                  <div style="text-align: right;">
                      <h3 style="font-size: 14pt; color: #1A202C; margin: 0;">${clinicInfo.name}</h3>
                      <p style="font-size: 9pt; color: #4A5568; margin: 2px 0;">${clinicInfo.address}</p>
                      <p style="font-size: 9pt; color: #4A5568; margin: 2px 0;">${clinicInfo.contact}</p>
                  </div>
              </div>
          </div>`,
      footerTemplate: `
                <div style="width: 100%; border-top: 1px solid #EAEAEA; padding: 10px 50px; box-sizing: border-box; display: flex; justify-content: space-between; align-items: center; font-family: Helvetica, Arial, sans-serif; font-size: 8pt; color: #aaaaaa;">
                    <span>This is a confidential medical report generated by ${clinicInfo.name}.</span>
                    <div>Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>
                </div>`,
    });

    await browser.close();
    return pdfBuffer;
  } catch (error) {
    console.error("Error generating PDF with Puppeteer:", error);
    if (browser) await browser.close();
    throw new Error("Could not generate PDF.");
  }
}
