export const diagnosisList = [
  "Myopia",
  "Hyperopia",
  "Astigmatism",
  "Presbyopia",
  "Amblyopia",
  "Strabismus",
  "Glaucoma",
  "Cataract",
  "Diabetic Retinopathy",
  "Age-Related Macular Degeneration",
  "Dry Eye Syndrome",
  "Keratoconus",
  "Conjunctivitis",
  "Blepharitis",
  "Uveitis",
  "Retinal Detachment",
  "Color Blindness",
  "Pterygium",
  "Pinguecula",
  "Chalazion",
  "Stye",
  "Other",
].sort();
