export const ishiharaTestPlatesConsistent = [
  {
    question: "What do you see?",
    normalVisionAnswer: "12",
    protanopiaAnswer: "12",
    deuteranopiaAnswer: "12",
    totalColorBlindnessAnswer: "12",
    plateNumber: 1,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "8",
    protanopiaAnswer: "6",
    deuteranopiaAnswer: "3",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 2,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "29",
    protanopiaAnswer: "70",
    deuteranopiaAnswer: "70",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 3,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "5",
    protanopiaAnswer: "2",
    deuteranopiaAnswer: "2",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 4,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "3",
    protanopiaAnswer: "5",
    deuteranopiaAnswer: "5",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 5,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "15",
    protanopiaAnswer: "17",
    deuteranopiaAnswer: "17",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 6,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "74",
    protanopiaAnswer: "21",
    deuteranopiaAnswer: "21",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 7,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "6",
    protanopiaAnswer: "nothing",
    deuteranopiaAnswer: "nothing",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 8,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "45",
    protanopiaAnswer: "nothing",
    deuteranopiaAnswer: "nothing",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 9,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "5",
    protanopiaAnswer: "nothing",
    deuteranopiaAnswer: "nothing",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 10,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "7",
    protanopiaAnswer: "nothing",
    deuteranopiaAnswer: "nothing",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 11,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "16",
    protanopiaAnswer: "nothing",
    deuteranopiaAnswer: "nothing",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 12,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "73",
    protanopiaAnswer: "nothing",
    deuteranopiaAnswer: "nothing",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 13,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "nothing",
    protanopiaAnswer: "5",
    deuteranopiaAnswer: "5",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 14,
  },
  {
    question: "What do you see?",
    normalVisionAnswer: "nothing",
    protanopiaAnswer: "45",
    deuteranopiaAnswer: "45",
    totalColorBlindnessAnswer: "nothing",
    plateNumber: 15,
  },
  {
    question: "What number do you see?",
    normalVisionAnswer: "26",
    protanopiaAnswer: "6",
    deuteranopiaAnswer: "2",
    protanomalyAnswer: "both_6_clearer",
    deuteranomalyAnswer: "both_2_clearer",
    totalColorBlindnessAnswer: "other", // Assuming they might not see a clear number
    plateNumber: 16,
  },
  {
    question: "What number do you see?",
    normalVisionAnswer: "42",
    protanopiaAnswer: "2",
    deuteranopiaAnswer: "4",
    protanomalyAnswer: "both_2_clearer",
    deuteranomalyAnswer: "both_4_clearer",
    totalColorBlindnessAnswer: "other",
    plateNumber: 17,
  },
  {
    question:
      "Trace the winding lines between the two x's Which line(s) did you follow?",
    normalVisionAnswer: "both_equal",
    protanopiaAnswer: "purple_only",
    deuteranopiaAnswer: "red_only",
    protanomalyAnswer: "both_purple_easier",
    deuteranomalyAnswer: "both_red_easier",
    totalColorBlindnessAnswer: "neither",
    plateNumber: 18,
  },
  {
    question:
      "Trace the winding line between the two 's Were you able to follow it?",
    normalVisionAnswer: "line_not_followed",
    protanopiaAnswer: "line_followed",
    deuteranopiaAnswer: "line_followed",
    totalColorBlindnessAnswer: "line_not_followed",
    plateNumber: 19,
  },
  {
    question:
      "Trace the winding line between the two X's Which line did you follow?",
    normalVisionAnswer: "bluish_green",
    colorVisionDeficiencyAnswer: [
      "no_clear_line",
      "different_line_specify",
      "different_line_described",
    ],
    totalColorBlindnessAnswer: "no_clear_line",
    plateNumber: 20,
  },
  {
    question:
      "Trace the winding line between the two x's Which line did you follow?",
    normalVisionAnswer: "orange",
    colorVisionDeficiencyAnswer: [
      "no_clear_line",
      "different_line_specify",
      "different_line_described",
    ],
    totalColorBlindnessAnswer: "no_clear_line",
    plateNumber: 21,
  },
  {
    question:
      "Trace the winding line between the two X's Which line did you follow?",
    normalVisionAnswer: "bluish_green_yellowish_green",
    redGreenDeficiencyAnswer: "bluish_green_purple",
    totalColorBlindnessAnswer: "no_line",
    plateNumber: 22,
  },
  {
    question:
      "Trace the winding line between the two X's Which line did you follow?",
    normalVisionAnswer: "purple_orange",
    redGreenDeficiencyAnswer: "purple_bluish_green",
    totalColorBlindnessAnswer: "no_line",
    plateNumber: 23,
  },
  {
    question:
      "Trace the winding line between the two X's Were you able to follow it?",
    normalVisionAnswer: "line_followed",
    colorVisionDeficiencyAnswer: "line_followed",
    totalColorBlindnessAnswer: "line_followed",
    plateNumber: 24,
  },
];
